import type { Model } from "./types";

const initModel: Model = {
  title: "",
  year: "",
  rated: "",
  released: "",
  runtime: "",
  genre: "",
  director: "",
  writer: "",
  actors: "",
  plot: "",
  language: "",
  country: "",
  awards: "",
  poster: "",
  ratings: [
    {
      source: "",
      value: "",
    },
  ],
  metascore: "",
  imdbRating: "",
  imdbVotes: "",
  imdbid: "",
  type: "",
  totalSeasons: "",
  response: "",
  isLoading: false,
  currentEpisode: {
    title: "",
    released: "",
    episode: "",
    imdbid: "",
    imdbRating: "",
    actors: "",
    awards: "",
    country: "",
    director: "",
    genre: "",
    language: "",
    metascore: "",
    plot: "",
    poster: "",
    rated: "",
    ratings: [],
    response: "",
    runtime: "",
    season: "",
    type: "",
    writer: "",
    year: "",
    imdbvotes: "",
    seriesid: "",
  },
  episodes: [],
  currentIndex: 0,
};

export default initModel;
